In [7]:
import numpy as np
print(np.__version__)

2.3.5


In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[[4, 5, 6],[1, 2, 3]],[[4, 5, 6],[1, 2, 3]]])
c = a + b
print(c)

[[[5 7 9]
  [2 4 6]]

 [[5 7 9]
  [2 4 6]]]


In [10]:
print(a.shape)
print(a.size)

(3,)
3


In [14]:
# 과일 판매량에 10% 할인 이벤트 적용
sales_q1 = np.array([200, 340, 150, 400])
discounted = sales_q1 * 0.9

print(discounted)


[180. 306. 135. 360.]


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [18]:
arr = np.zeros((2, 3))
print(arr)



[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr = np.ones((3, 2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [27]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [28]:
arr = np.random.randn(2, 3)
print(arr)

[[ 2.09428819e+00 -1.46995818e-03 -3.96572764e-01]
 [-1.58411025e-01 -8.67157668e-01  5.31176571e-01]]


In [30]:
arr = np.array([[1,2,3], [4, 5, 6]])
print(arr.shape)    # 배열의 구조

print(arr.ndim)     # 배열의 차원

print(arr.dtype)

(2, 3)
2
int64


NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [42]:
arr = np.zeros((4, 3))  # 2x3 배열
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
arr = np.zeros((3, 3))  # 3x3 배열
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
arr = np.zeros((0, 20, 5))  # 3x3 배열
print(arr)

[]


In [46]:
# 1차원 배열 인덱싱

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])

10
30


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1])  # 0번째 행, 1번째 열의 요소 출력 (2)
print(arr[2, 2])  # 2번째 행, 2번째 열의 요소 출력 (9)

2
9


In [54]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 0, 0])  # 1번째 차원, 0번째 행, 2번째 열의 요소 출력 (9)
print(arr[0, 1, 1])
print(arr[1, 1, 2])

7
5
12


In [56]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])

[20 30 40]
[10 20 30]


In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1:, :2])  # 1번째 행부터 끝까지, 0번째와 1번째 열만 출력 ([[4, 5], [7, 8]])

[[4 5]
 [7 8]]


In [58]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[:, 1, :2])  # 각 차원에서 1번째 행의 처음 두 열 출력 ([[4, 5], [10, 11]])

[[ 4  5]
 [10 11]]


In [59]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # 0번째, 2번째, 4번째 인덱스를 선택
print(arr[idx])   # [10, 30, 50]

[10 30 50]


In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])  # [3, 5, 7]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 5 7]


분리형 인덱스

In [62]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 30])  # [40, 50]

[10 20 30 40 50]


1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

In [133]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [139]:
print(arr[:,1])
print(arr[1, 2])
print(arr[:2, :2])

[20 50 80]
60
[[10 20]
 [40 50]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

In [141]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])


In [142]:
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [ ]:
arr = np.array(arr[:6:2])
print(arr[arr > 30])

어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [147]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

In [ ]:
print(sales >= 200)
print(sales []

In [150]:
print(sales[:,1]<= 100)

[False  True False  True False]


In [151]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))  # 1*4 + 2*5 + 3*6 = 32

32


In [152]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = np.array([5, 6])
print(np.dot(arr2d, arr1d))
# [1*5 + 2*6, 3*5 + 4*6]
# [17, 39]

[17 39]


In [153]:
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr2d_1, arr2d_2))
# [[1*5 + 2*7, 1*6 + 2*8],
#  [3*5 + 4*7, 3*6 + 4*8]]
# [[19, 22],
#  [43, 50]]

[[19 22]
 [43 50]]


In [154]:
# 스칼라 값과의 연산
arr = np.array([1, 2, 3])
print(arr + 10)


[11 12 13]


In [ ]:
arr2d = np.array(
    [[1, 2, 3], 
     [4, 5, 6]]
    )


arr1d = np.array([1, 2, 3])
print()
print(arr2d + arr1d)
# [[2, 4, 6],
#  [5, 7, 9]]

In [155]:
arr3d = np.random.rand(3, 1, 4)  # 3x1x4 배열
arr2d = np.random.rand(4, 4)     # 4x4 배열

# 브로드캐스팅을 통해 3차원 배열과 2차원 배열 간 연산 수행
result = arr3d + arr2d
print(result.shape)  # 결과: 3x4x4 배열

(3, 4, 4)


In [156]:
arr2d = np.array(
    [[1, 2, 3], 
     [4, 5, 6]]
    )


row = np.array([10, 20, 30])
col = np.array(
    [[10],
     [20]]
)

print(arr2d.shape)
print(row.shape)
print(col.shape)

print(arr2d + row)
print(arr2d + col)



(2, 3)
(3,)
(2, 1)
[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


In [159]:
arr = np.array([10, 20, 30])
print(arr > 15)

[False  True  True]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
print(arr1 > arr2)  # [False, False, True]

In [160]:
print(arr.max())  # 5
print(arr.min())  # 1

30
10


In [161]:
print(arr.mean())  # 3.0

20.0


In [163]:
print(arr.std())  # 표준편차
print(arr.var())  # 분산

8.16496580927726
66.66666666666667


In [164]:
print(arr.cumsum())  # [1, 3, 6, 10, 15]

[10 30 60]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.sum(axis=0))  # [5, 7, 9] (각 열의 합)
print(arr2d.sum(axis=1))  # [6, 15] (각 행의 합)

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [165]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 +arr2)
print(arr1 -arr2)
print(arr1 *arr2)
print(arr1 // arr2)


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10 10 10 10]


다음 두 배열 간의 내적 연산을 수행하세요.

In [168]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.dot(arr1, arr2))

32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [169]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

In [173]:
arr = np.array([10, 20, 30, 40, 50])

print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.sum() // 5)



150
50
10
30


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.

In [183]:
arr = np.array([10, 20, 30, 30, 40, 50, 60])

In [196]:
import numpy as np
from scipy import stats


print(np.mean(arr))
print(np.median(arr))
print(np.stats.mode(arr))
print(np.var(arr))
print(np.std(arr))
print(np.std(max) - np.std(min))

ModuleNotFoundError: No module named 'scipy'

정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [197]:
arr = np.random.randn(1000)
print(np.mean(arr))
print(np.std(arr))

-0.01856546209026825
0.9604103412543084


In [199]:
uniform_arr = np.random.uniform(0, 1, 1000)
print(np.mean(uniform_arr), np.std(uniform_arr))

0.49363928365846277 0.28528408721732373


아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.

In [200]:
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]


result = np.array([scores_math, scores_english, scores_science])
print(result)



[[88 92 76 85 95 92 88 90 85 88]
 [90 85 80 87 92 89 83 91 86 88]
 [85 88 82 89 94 86 91 88 84 87]]


In [202]:
score_mean = np.mean(result, axis=0)
print(socre_mean)


[87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]
11.89333333333335


In [204]:
score_var = np.var(result, axis=0)
print(score_var)

[ 4.22222222  8.22222222  6.22222222  2.66666667  1.55555556  6.
 10.88888889  1.55555556  0.66666667  0.22222222]


In [205]:
score_std = np.std(result, axis=0)
print(score_std)

[2.05480467 2.86744176 2.49443826 1.63299316 1.24721913 2.44948974
 3.29983165 1.24721913 0.81649658 0.47140452]


In [207]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)  # [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [ ]:
arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)
print(sorted_indices)  # [1, 2, 0] (정렬된 순서의 인덱스)

# 인덱스를 사용하여 배열을 정렬
print(arr[sorted_indices])  # [10, 20, 30]

다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.

In [208]:
arr = np.array([50, 10, 30, 40, 20])
sorted_arr = np.sort(arr)
print(sorted_arr)

sorted_arr_desc = np.sort(arr)[::-1]
print(sorted_arr_desc)  


[10 20 30 40 50]


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.

In [209]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
sorted_arr_axis0 = np.sort(arr2d, axis=0)
print(sorted_arr_axis0)
sorted_arr_axis1 = np.sort(arr2d, axis=1)
print(sorted_arr_axis1)

[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.

In [210]:
arr = np.array([15, 10, 20])

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)  # [1, 2, 3, 4, 5, 6]

In [211]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)
# [[1, 2, 3],
#  [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [212]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)
# [[1, 2, 3],
#  [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.

In [216]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)  
hastack_arr = np.concatenate((arr1, arr2))
print(hastack_arr)  

[1 2 3 4 5 6]
[1 2 3 4 5 6]


다음 두 개의 1차원 배열을  np.vstack()을 사용하여  병합하세요.

In [217]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

hastack_arr = np.concatenate((arr1, arr2))
print(hastack_arr)  

[1 2 3 4 5 6]


In [218]:
import time
size = 1_000_000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]

print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.13485217094421387


In [219]:
size = 100_000_000  # 1억 개의 요소
arr = np.random.rand(size)  # 난수 배열 생성

start_time = time.time()
result = np.sum(arr)  # 배열의 합 계산
print("대용량 데이터 합계 성능:", time.time() - start_time)

대용량 데이터 합계 성능: 0.06402182579040527


In [220]:
# 1GB 크기의 파일을 생성 후 메모리 맵핑 방식으로 읽기
size = 10**9
arr = np.memmap('large_file.dat', dtype='float32', mode='w+', shape=(size,))
arr[:100] = np.random.rand(100)  # 일부 데이터를 파일에 쓰기

# 파일을 메모리 맵핑하여 읽기
memmap_arr = np.memmap('large_file.dat', dtype='float32', mode='r', shape=(size,))
print(memmap_arr[:10])  # 메모리에 로드된 일부 데이터

[0.01325294 0.55630517 0.9865505  0.15578057 0.20097691 0.44178358
 0.92979646 0.15661462 0.7943276  0.6672934 ]


다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.

2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

In [3]:
# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
import numpy as np

sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5s
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.

In [5]:
print(sales_data.shape)
sales_avg = sales_data.mean(axis=2)
print(sales_avg)


(5, 3, 6)
[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]


2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.

In [31]:
sales_data_max = np.max(sales_data,axis=0)
print(sales_data_max)
print(sales_data_max.shape)


month_max = np.max(sales_data_max,axis=0)
print(month_max)
max_index = np.argmax(sales_data_max,axis=0)
print(max_index)
fruits = np.array(["사과", "바나나", "오렌지"])
print(fruits[max_index])

[[130 150 200 230 180 210]
 [110 140 170 190 160 180]
 [100 120 160 140 130 150]]
(3, 6)
[130 150 200 230 180 210]
[0 0 0 0 0 0]
['사과' '사과' '사과' '사과' '사과' '사과']


3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.

4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.